image: golang:1.12

pipelines:
  default:
    # - step:
    #     name: Compiling
    #     script:
    #       - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
    #       - mkdir -pv "${PACKAGE_PATH}"
    #       - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
    #       - ls
    #       - cd "${PACKAGE_PATH}"
    #       - go get -v
    #       - go build -v
    #       - go test -v
    - step:
        name: Build and deploy
        script:
          - ls
          - git archive --format=tar.gz master -o ${HEROKU_APP_NAME}.tar.gz
          - pipe: atlassian/heroku-deploy:1.1.4
            variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: ${HEROKU_APP_NAME}.tar.gz
                WAIT: "true"
                DEBUG: "true"
